# - method_names : [ensemble, dropconnect, dropout, flipout, mcdropconnect, mcdropout]
- method_names : [duq]

- metrics : ['accuracy', 'predictive-entropy', 'shannon-entropy', 'mutual-information']

- keys : ['test', 'lockbox']